[package]
name = "whatisyourconvention"
version = "0.1.0"
authors = ["KBuild <qwer7995@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
walkdir = "2.3"
heck = "0.3.2"